[workspace]
members = [
    "ircd_macros",
    "ircd_sync",
    "irc_network",
    "irc_server",
    "irc_strings",
    "ircd",
    "rpc_protocols",
    "client_listener",
]

# Incremental builds break inventory
[profile.dev]
incremental = false

