[workspace]
members = [
    "sable_macros",
    "sable_network",
    "sable_ircd",
    "client_listener",
    "auth_client",
    "sable_ipc",
    "sable_server",
    "sable_services",
]

# Incremental builds break inventory
[profile.dev]
incremental = false
panic = "abort"
