[package]
name = "ircd"
version = "0.1.0"
edition = "2018"

[workspace]
members = [ "ircd_macros" ]

[dependencies]
ircd_macros = { path = "ircd_macros" }
log = "0.4"
simple_logger = "1"
futures = "0.3"
async-std = "1.7"
triggered = "0.1"