[workspace]
members = [
    "ircd_macros",
    "sable_network",
    "sable_ircd",
    "ircd",
    "client_listener",
    "auth_client",
    "sable_ipc",
]

# Incremental builds break inventory
[profile.dev]
incremental = false
panic = "abort"
