[package]
name = "sable_history"
version = "0.1.0"
edition = "2021"
build = "build.rs"

[build-dependencies]
built = { version = "0.5", features = [ "git2" ] }

[dependencies]
sable_macros = { path = "../sable_macros" }
sable_network = { path = "../sable_network" }
thiserror = "1"
