[package]
name = "irc_strings"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
convert_case = "0.4"
wildmatch = "2.1"

[dependencies.serde]
version = "1"
features = [ "derive" ]