
/// An update to be applied by the event log.
#[derive(Debug)]
pub enum EventLogUpdate
{
    /// Create and apply a new `Event`. Note that only the target and details
    /// are specified here; other fields are generated by the event log itself
    /// based on its current state.
    NewEvent(irc_network::ObjectId, irc_network::event::EventDetails),
}
