
/// An update to be applied by the event log.
#[derive(Debug)]
pub enum EventLogUpdate
{
    /// Create and apply a new `Event`. Note that only the target and details
    /// are specified here; other fields are generated by the event log itself
    /// based on its current state.
    NewEvent(irc_network::ObjectId, irc_network::event::EventDetails),

    /// Notify the sync layer that a server has left the network. No new events
    /// should be sent to or accepted from it until it restarts with a new epoch.
    ServerQuit(irc_network::ServerName, irc_network::ServerId, irc_network::EpochId),

    /// Notify that a server has joined the network and is eligible to have events
    /// sent to it
    ServerJoin(irc_network::ServerName, irc_network::ServerId, irc_network::EpochId),
}
