[package]
name = "ircd_macros"
version = "0.1.0"
edition = "2018"

[lib]
proc-macro = true


[dependencies]
quote = "1"
proc-macro2 = "1"
convert_case = "0.4"

[dependencies.syn]
version = "1"
features = [ "full", "extra-traits" ]