name: CI

on: [push, pull_request]

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest

    strategy:
      matrix:
        rust:
        - nightly

    steps:
      - name: Checkout sources
        uses: actions/checkout@v2

      - name: Install rust (${{ matrix.rust }})
        uses: actions-rs/toolchain@v1
        with:
          toolchain: ${{ matrix.rust }}
          profile: minimal
          override: true

      - name: Enable Cargo cache
        uses: Swatinem/rust-cache@v2

      - name: Build
        uses: actions-rs/cargo@v1
        with:
          command: build
          args: ${{ matrix.features }}

      - name: Test
        uses: actions-rs/cargo@v1
        with:
          command: test
          args: ${{ matrix.features }}

      - name: Doc
        run: RUSTDOCFLAGS="--enable-index-page -Zunstable-options" cargo doc ${{ matrix.features }} --no-deps

      - name: Upload documentation
        uses: actions/upload-pages-artifact@v3
        id: gh-pages-documentation
        # don't run on pull requests
        if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/master' }}
        with:
          path: "target/doc"

  lint:
    name: Linting
    runs-on: ubuntu-latest

    steps:
      - name: Checkout sources
        uses: actions/checkout@v2

      - name: Install rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly
          components: rustfmt, clippy
          profile: minimal
          override: true

      - name: cargo fmt -- --check
        uses: actions-rs/cargo@v1
        with:
          command: fmt
          args: -- --check

      - name: cargo clippy
        uses: actions-rs/cargo@v1
        with:
          command: clippy
          args: --all-targets

  deploy:
    name: Deploy
    needs: test
    runs-on: ubuntu-latest
    # don't run on pull requests
    if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/master' }}

    permissions:
      pages: write
      id-token: write

    steps:
      - name: Deploy to GitHub Pages
        id: gh-pages-documentation
        uses: actions/deploy-pages@v4
