name: "Run integration tests"
on:
  pull_request:
  push:
jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: cachix/install-nix-action@v20
      with:
        nix_path: nixpkgs=channel:nixos-unstable
        extra_nix_config: "system-features = nixos-test benchmark big-parallel kvm"
    - uses: DeterminateSystems/magic-nix-cache-action@v2
    - run: nix flake check -L
